session_name: config-nvim
windows:
  - layout: b241,193x41,0,0,4
    options:
      "@tmux_window_name_enabled": 0
    panes:
      - focus: "true"
        shell_command: htop
    start_directory: /home/jacko
    window_name: htop
  - focus: "true"
    layout: adc2,192x40,0,0,5
    options:
      "@tmux_window_name_enabled": 1
    panes:
      - pane
    start_directory: /home/jacko/.config/nvim
    window_name: espeak-ng What are y
