;;; nix-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from nix-ts-mode.el

(autoload 'nix-ts-mode "nix-ts-mode" "\
Major mode for editing Nix expressions, powered by treesitter.

\\{nix-ts-mode-map}

(fn)" t)
(register-definition-prefixes "nix-ts-mode" '("nix-ts-"))

;;; End of scraped data

(provide 'nix-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nix-ts-mode-autoloads.el ends here
